Normalized criticality score
- Made some changes to normalize the criticality score. Did not manage to test it, since I get some errors:
- fmean is not possible to import... now I do import mean as fmean
- also

File "C:\Users\steffejb\OneDrive - NTNU\Work\GitHub\FOMO-sim\fomo\sim\State.py", line 226, in get_vehicle_travel_time
    if self.traveltime_vehicle_matrix_stddev is not None:

AttributeError: 'State' object has no attribute 'traveltime_vehicle_matrix_stddev'